events { worker_connections 1024; }

http {
    upstream ticket_servers {
        # Nginx bakal bagi beban ke dua kontainer ini bergantian
        server ticket_service_1:3000;
        server ticket_service_2:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://ticket_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}